name: Terraform Format
description: Checks the terraform formatting, formats if broken and pushes the changes back to the branch. 
inputs:
  terraform-version:
    description: "Install the version of terraform. By default (empty) use .terraform-version file"
    default: ""
  fix-format:
    description: "Auto fix broken formatting and push a commit"
    default: false

runs:
  using: "composite"
  steps:
    - name: Set TERRAFORM_VERSION
      shell: bash
      run: |
        if [[ -n "${{ inputs.terraform-version }}" ]]; then
          echo "TERRAFORM_VERSION=${{ inputs.terraform-version }}" >> $GITHUB_ENV
        else
          if [[ ! -f .terraform-version ]]; then
            echo "::error::No .terraform-version found and input terraform-version not set"
            exit 10
          fi
          echo "TERRAFORM_VERSION=`cat .terraform-version`" >> $GITHUB_ENV
        fi

    - name: Terraform Install
      shell: bash
      run: |
        OS=linux
        ARCH=amd64
        zipFile="terraform_${TERRAFORM_VERSION}_${OS}_$ARCH.zip"
        echo Installing terraform v$TERRAFORM_VERSION $zipFile
        wget --no-verbose "https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/$zipFile"
        unzip -o "$zipFile"
        rm -f "$zipFile"
        ./terraform version

    - name: Terraform Format Check
      shell: bash
      env:
        INPUT_FIX_FORMAT: ${{ inputs.fix-format }}
      run: |
        echo Checking Terraform format
        if ./terraform fmt -check -diff -recursive; then
          echo "Terraform is properly formatted"
          exit 0
        fi
        if [[ $INPUT_FIX_FORMAT != true ]]; then
          echo
          echo ::error::Terraform formatting errors detected. See log for diff with detail. To fix, run locally: terraform fmt -recursive
          echo
          exit 10
        fi

        echo "Running Terraform format"
        ./terraform fmt -recursive

        if git diff-index --quiet HEAD --; then
            echo No changes
            exit 0
        fi
        # Use the current commits author
        git config user.name "$(git log -1 --pretty=format:%an)"
        git config user.email "$(git log -1 --pretty=format:%ae)"
        git commit -a -m "AutoFix: Terraform format"
        git show -s | cat
        git push
